name: Run CI Build

on:
  push:
    branches:
      - master

jobs:
  ci_build:
    runs-on: ubuntu-latest
    name: NWN:EE CI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build module
        uses: Ardesco/nasher4gh@v1
